# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-16 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRevisionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('SUBMITTED_FOR_MODERATION', 'Submitted for moderation'), ('PUBLISH', 'Published'), ('UNPUBLISH', 'Unpublished'), ('MODERATION_APPROVED', 'Moderation approved'), ('MODERATION_REJECTED', 'Moderation rejected')], max_length=40, null=True)),
                ('event_json', models.TextField(null=True, verbose_name='event JSON, contains optional metadata about event')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='created at')),
            ],
        ),
        migrations.AddField(
            model_name='pagerevision',
            name='_changed_fields',
            field=models.TextField(blank=True, null=True, verbose_name='changed fields JSON'),
        ),
        migrations.AddField(
            model_name='pagerevisionevent',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_events', to='wagtailcore.PageRevision', verbose_name='page revision'),
        ),
        migrations.AddField(
            model_name='pagerevisionevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
